### ISSUE TITLE
The font isn't font size isn't matching the original in website. After downloading.

### ISSUE THREAD

**Issue by GrishMahat** [KrishnaCodez/MagicText#8]
![magictext](https://github.com/user-attachments/assets/a4ea66c6-5d99-4d5f-8c1b-127370150b2f)
![image](https://github.com/user-attachments/assets/0bd9cbd6-b529-4122-b1e5-77c516b2c657)
The font isn't font size isn't matching the original in website. After downloading.

**Comment by KrishnaCodez** [comment]
There's currently a bug I'm working on fixing. As a workaround, you can increase the preview size so that it appears smaller when downloaded.

**Comment by KrishnaCodez** [comment]
hey @GrishMahat the font issue is now fixed with whole experience and interesting features.
